trigger: none # Manual trigger only

variables:
  - group: 'Common-Variables'
  - name: 'solution'
    value: 'CleanArchitecture.sln'

stages:
- stage: Deploy_Development
  displayName: 'Deploy to Development'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  variables:
    - group: 'Development-Variables'
  jobs:
  - deployment: Deploy
    environment: 'development'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deploy-steps.yml
            parameters:
              environmentName: 'Development'
              azureSubscription: '$(azureSubscription)'
              appServiceName: '$(appServiceName)-dev'

- stage: Deploy_Test
  displayName: 'Deploy to Test'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    - group: 'Test-Variables'
  jobs:
  - deployment: Deploy
    environment: 'test'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deploy-steps.yml
            parameters:
              environmentName: 'Test'
              azureSubscription: '$(azureSubscription)'
              appServiceName: '$(appServiceName)-test'

- stage: Deploy_Acceptance
  displayName: 'Deploy to Acceptance'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    - group: 'Acceptance-Variables'
  jobs:
  - deployment: Deploy
    environment: 'acceptance'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deploy-steps.yml
            parameters:
              environmentName: 'Acceptance'
              azureSubscription: '$(azureSubscription)'
              appServiceName: '$(appServiceName)-acc'

- stage: Deploy_Production
  displayName: 'Deploy to Production'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    - group: 'Production-Variables'
  jobs:
  - deployment: Deploy
    environment: 'production'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deploy-steps.yml
            parameters:
              environmentName: 'Production'
              azureSubscription: '$(azureSubscription)'
              appServiceName: '$(appServiceName)-prod' 